env:
  es6: true
  node: true
extends: 'prettier'
rules:
  linebreak-style:
    - error
    - windows
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  no-unused-vars:
    - off
  no-console:
    - off